### ISSUE TITLE
Any way to use with docker compose?

### ISSUE THREAD

**Issue by yuangao0317** [dennzimm/npmrc-replace-env#29]
I tried to set env_file: in docker compose
I tried to set environment: in docker compose
I tried to COPY .env ./ in dockerfile
But still getting error:
3.230 > npx npmrc-replace-env
3.230
3.720 /app/node_modules/npmrc-replace-env/dist/cli.js:44
3.720     throw new Error(
3.720     ^
3.720
3.720 Error: Environment variable NPMRC_NPM_TOKEN is not defined. Please define it in your .env file or pass it as an environment variable.
3.720     at getEnvValue (/app/node_modules/npmrc-replace-env/dist/cli.js:44:11)
3.720     at /app/node_modules/npmrc-replace-env/dist/cli.js:55:49
3.720     at Array.forEach (<anonymous>)
3.720     at generateNpmrc (/app/node_modules/npmrc-replace-env/dist/cli.js:54:8)
3.720     at writeNpmrc (/app/node_modules/npmrc-replace-env/dist/cli.js:90:17)
3.720     at Object.<anonymous> (/app/node_modules/npmrc-replace-env/dist/cli.js:120:1)
3.720     at Module._compile (node:internal/modules/cjs/loader:1480:14)
3.720     at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
3.720     at Module.load (node:internal/modules/cjs/loader:1287:32)
3.720     at Module._load (node:internal/modules/cjs/loader:1103:12)
3.720
3.720 Node.js v22.1.0
3.733 npm error code 1
3.733 npm error path /app
3.735 npm error command failed
3.735 npm error command sh -c npx npmrc-replace-env

**Comment by dennzimm** [comment]
Do you have a (minimally reproducible) example for me? Maybe I can have a look at it then. Could it be that your environment variables are not being forwarded correctly?

**Comment by dennzimm** [comment]
I’m closing this issue due to inactivity. If the problem persists or you have further details to share, feel free to reopen the issue or create a new one. Thanks!
